[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "production"

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.1"
